server:
  port: 7202
  servlet:
    context-path: /converter

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers,metrics,beans,mappings,threaddump,heapdump,swagger-ui,sbom

github:
  staging:
    directory: ${GITHUB_STAGING_DIR:/Users/steveroach/development/docops/asciidoc-staging}
  web:
    directory: ${GITHUB_WEB_DIR:/Users/steveroach/development/docops/asciidoc-web}
  disable:
    ssl:
      validation: ${GITHUB_DISABLE_SSL:false}

converter:
  panel-server: http://localhost:8010/extension
  panel-webserver: http://localhost:8010/extension
  local-debug: true
  default-formats:
    - html
  epub-settings:
    title: "Generated EPUB"
    authors:
      - "Steve Roach"
    language: "en"
    cover-image-path: ""
    toc-level: 2
    validate-output: false
    resource-inclusion:
      include-images: true
      include-fonts: true
      include-stylesheets: true
      max-image-size: 10485760

sitemap:
  directory-depth: ${SITEMAP_DIRECTORY_DEPTH:2}


app:
  execution-history:
    max-size: 10
  encryption:
    key: ${ENCRYPTION_KEY:your-32-character-secret-key-here}
  security:
    allowed-base-paths:
      - "/Users/steveroach/IdeaProjects"
      - "/tmp/asciidoc-conversion"
      - "/usr/local/docops/stage/docops.io"

spring:
  threads:
    virtual:
      enabled: true

logging:
  file:
    name: logs/application.log
    # OR use path (but not both)
    # path: logs/
  level:
    root: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      # Rotate when file reaches this size
      max-file-size: 5MB
      # Keep this many historical files
      max-history: 10
      # Total size of all log files combined
      total-size-cap: 250MB
      # Pattern for archived file names
      file-name-pattern: logs/application-%d{yyyy-MM-dd}.%i.log.gz
      # Clean up old files on application startup
      clean-history-on-start: true
